[package]
name = "grairc"
version = "0.1.0"
edition = "2024"

[dependencies]
ctru-rs = { git = "https://github.com/rust3ds/ctru-rs" }
tokio = "1.49.0"

[package.metadata.cargo-3ds]
romfs_dir = "romfs"
description = "grairc"
authors = ["electron271"]
icon_path = "metadata/icon.png"
